services:
  webserver:
    image: koenkoreman/backend_labspentesting
    container_name: labsPentesting
    command: /bin/sh -c "service apache2 start;tail -f /dev/null"
    ports:
      - "80:80"
      - "443:443"